name: 'codefacilitators'
description: 'Assign reviewers to a PR based on the files that were changed.'
author: '0xtekgrinder'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'git-pull-request'
  color: 'gray-dark'

# Define your inputs here.
inputs:
  token:
    description: 'github token'
    required: true
  file:
    description: 'file to be checked'
    required: true
    default: '.github/CODEFACILITATORS'
  add_groups_directly:
    description: 'If true, adds teams as reviewers directly instead of their members'
    required: false
    default: 'false'

# Define your outputs here.
outputs:
  reviewers:
    description: 'reviewers'

runs:
  using: node20
  main: dist/index.js
